[package]
name = "hello_guess_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ^ 说明是和 0.3.14 兼容的任意版本
rand = "^0.7.0"
